---
name: ShellCheck
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
env:
  # some scripts source tox-lsr scripts - suppress that check
  SHELLCHECK_OPTS: -e SC1091
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run ShellCheck
        id: shellcheck_id
        uses: ludeeus/action-shellcheck@master
      - name: Show file paths scanned
        run: |
          echo Files scanned:
          echo "${{ steps.shellcheck_id.outputs.files }}"
