# yamllint disable rule:line-length
name: Check for non-inclusive language
on:  # yamllint disable-line rule:truthy
  - pull_request
jobs:
  woke:
    name: woke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: woke
        uses: get-woke/woke-action@v0
        with:
          woke-args: "-c https://raw.githubusercontent.com/linux-system-roles/tox-lsr/main/src/tox_lsr/config_files/woke.yml"
          # Cause the check to fail on any broke rules
          fail-on-error: true
