#!/usr/bin/env bash

# This script is intended to be used as git pre-commit hook.
# Make sure file is executable and copy it into <your repo>/.git/hooks/
# This script has to be used together with post-commit to work properly.

GITPATH=$(git rev-parse --show-toplevel)

touch "$GITPATH/.commit"
